language: ruby
rvm:
- 2.0.0-p481
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: dKekkVUoszGZKmnWNlbmQAVwIjzbXEqSMdFmXiEA5krh7qaINHgs34hfJURTy2nfBcBSisKEJUSVtMxHs0DjFZEO5QhscTXmuGxKGpSY/l1Kuw5Wq7vCfjdzfvv/XXOdvw41rBfiR6xeV0wiWeGf9am5DX4etSpeA+ZyOFJlSz8=
  app: order-of-the-stars111 #add in my heroku app name
  run:
    - "rake db:migrate"
    - restart
